# Generated by Django 4.0.4 on 2022-05-30 03:36

from django.db import migrations, models
import pacientes.models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='image_selfie',
            field=models.ImageField(blank=True, null=True, upload_to=pacientes.models.image_paciente),
        ),
    ]
